name: PHP Composer


on:
  push:
    branches:
      - main
      - GiordanoT
      - GianlucaDM
      - Federico
      - DavPalo
  pull_request:
    branches:       
      - main
      - GiordanoT
      - GianlucaDM
      - Federico
      - DavPalo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
env:
  DB_DATABASE: globex_corporation
  DB_USER: root
  DB_PASSWORD: root

steps:
  - name: Set up MySQL
    run: |
      sudo /etc/init.d/mysql start
      mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}