name: PHP Composer


on:
  push:
    branches:
      - main
      - GiordanoT
      - GianlucaDM
      - Federico
      - DavPalo
  pull_request:
    branches:
      - main
      - GiordanoT
      - GianlucaDM
      - Federico
      - DavPalo

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: globex_corporation
          MYSQL_USER: localhost
          MYSQL_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 33306:3306
        #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
